---
# Direct zone
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: Zone
metadata:
  name: helloworld.com
  namespace: default
spec:
  nameservers:
    - ns1.helloworld.com
    - ns2.helloworld.com
  kind: Native

---
# Reverse Zone
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: Zone
metadata:
  name: 1.168.192.in-addr.arpa
spec:
  nameservers:
    - ns1.helloworld.com
    - ns2.helloworld.com
  kind: Native

---
# Specific Catalog
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: Zone
metadata:
  name: example1.com
  namespace: example1
spec:
  catalog: catalog.test
  nameservers:
    - ns1.example1.com
    - ns2.example1.com
  kind: Master

---
# Specific SOA_EDIT_API
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: Zone
metadata:
  name: example2.com
  namespace: example2
spec:
  catalog: catalog.test
  nameservers:
    - ns1.example2.com
    - ns2.example2.com
  kind: Master
  soa_edit_api: EPOCH

---
# Specific Catalog
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: Zone
metadata:
  name: example1.com
  namespace: example3
spec:
  catalog: catalog.test
  nameservers:
    - ns1.example1.com
    - ns2.example1.com
  kind: Master
