---
# Direct zone
apiVersion: dns.cav.enablers.ob/v1alpha1
kind: Zone
metadata:
  labels:
    app.kubernetes.io/name: powerdns-operator
    app.kubernetes.io/managed-by: kustomize
  name: helloworld.com
spec:
  nameservers:
    - ns1.helloworld.com
    - ns2.helloworld.com
  kind: Native

---
# Reverse Zone
apiVersion: dns.cav.enablers.ob/v1alpha1
kind: Zone
metadata:
  labels:
    app.kubernetes.io/name: powerdns-operator
    app.kubernetes.io/managed-by: kustomize
  name: 1.168.192.in-addr.arpa
spec:
  nameservers:
    - ns1.helloworld.com
    - ns2.helloworld.com
  kind: Native
